name: Dependency Submission

on:
  push:
    branches: ['main', 'develop']
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
      with:
        # The gradle project is not in the root of the repository.
        build-root-directory: tools
        # Exclude all dependencies that originate solely in the 'buildSrc' project
        dependency-graph-exclude-projects: 'toolkit'
        # Exclude dependencies that are only resolved in test classpaths
        dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'
